version: '2'
services: 
 kafka:
   build: .
   image: kafka-container
   ports:
     - "192.168.99.100:2181:2181"
     - "192.168.99.100:9092:9092"
   environment:
     KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100 
     KAFKA_BROKER_ID: 1 
 es1: 
    image: elasticsearch
    ports: 
     - "192.168.99.100:9200:9200"
     - "192.168.99.100:9300:9300"
 cas1: 
     image: elubow/cassandra
     ports: 
       - "192.168.99.100:9160:9160"
 titan:
    build: ./titan-gremlin
    image: elubow/titan
    links:
        - es1
        - cas1
    ports:
        - "192.168.99.100:8182:8182"
        - "192.168.99.100:8184:8184"

